
services:
    db:
      image: mysql
      restart: always
      ports:
        - 3308:3306
      env_file:
        - .env
      environment:
        - MYSQL_USER=user
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=myhousetask
