services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local