// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: family.sql

package store

import (
	"context"
	"database/sql"
)

const countFamilies = `-- name: CountFamilies :one
SELECT count(*)
FROM family_members fm
WHERE fm.user_id = ?
`

func (q *Queries) CountFamilies(ctx context.Context, userID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFamilies, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersFamilyMembers = `-- name: CountUsersFamilyMembers :one
SELECT COUNT(DISTINCT fm2.user_id)
FROM family_members AS fm1
         JOIN family_members AS fm2 ON fm1.family_id = fm2.family_id
WHERE fm1.user_id = ?
`

func (q *Queries) CountUsersFamilyMembers(ctx context.Context, userID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersFamilyMembers, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFamily = `-- name: CreateFamily :execresult
INSERT INTO families (name, description, owner_id) VALUES (?, ?, ?)
`

type CreateFamilyParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	OwnerID     sql.NullString `json:"owner_id"`
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFamily, arg.Name, arg.Description, arg.OwnerID)
}

const createFamilyMember = `-- name: CreateFamilyMember :exec
INSERT INTO family_members (id, family_id, user_id, role)
VALUES (?, ?, ?, ?)
`

type CreateFamilyMemberParams struct {
	ID       string         `json:"id"`
	FamilyID sql.NullInt32  `json:"family_id"`
	UserID   sql.NullString `json:"user_id"`
	Role     sql.NullString `json:"role"`
}

func (q *Queries) CreateFamilyMember(ctx context.Context, arg CreateFamilyMemberParams) error {
	_, err := q.db.ExecContext(ctx, createFamilyMember,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
		arg.Role,
	)
	return err
}

const dashboardPage = `-- name: DashboardPage :many
SELECT
    f.id as id_familia,
    f.name as nome_familia,
    DATE_FORMAT(f.created_at, '%Y-%m-%d %H:%i:%s') as created_at,
    f.is_active as status,
    (SELECT COUNT(*) FROM family_members WHERE family_id = f.id) as total_membros
FROM families f
WHERE f.id IN (
    SELECT family_id FROM family_members fm WHERE fm.user_id = ?
)
ORDER BY f.created_at DESC
LIMIT 5
`

type DashboardPageRow struct {
	IDFamilia    int32        `json:"id_familia"`
	NomeFamilia  string       `json:"nome_familia"`
	CreatedAt    string       `json:"created_at"`
	Status       sql.NullBool `json:"status"`
	TotalMembros int64        `json:"total_membros"`
}

func (q *Queries) DashboardPage(ctx context.Context, userID sql.NullString) ([]DashboardPageRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardPage, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardPageRow
	for rows.Next() {
		var i DashboardPageRow
		if err := rows.Scan(
			&i.IDFamilia,
			&i.NomeFamilia,
			&i.CreatedAt,
			&i.Status,
			&i.TotalMembros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFamiliesForUser = `-- name: ListFamiliesForUser :many
SELECT
    f.id, f.name, f.description, f.is_active, f.created_at, f.owner_id
FROM
    families f
        JOIN
    family_members fm ON f.id = fm.family_id
WHERE
    fm.user_id = ?
ORDER BY
    f.created_at DESC
`

type ListFamiliesForUserRow struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	OwnerID     sql.NullString `json:"owner_id"`
}

func (q *Queries) ListFamiliesForUser(ctx context.Context, userID sql.NullString) ([]ListFamiliesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listFamiliesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFamiliesForUserRow
	for rows.Next() {
		var i ListFamiliesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFamilies = `-- name: ListRecentFamilies :many
SELECT
    f.id as id_familia,
    f.name as nome_familia,
    DATE_FORMAT(f.created_at, '%Y-%m-%d %H:%i:%s') as created_at,
    f.is_active as status,
    COUNT(fm.id) as total_membros
from families f
LEFT JOIN family_members fm on fm.family_id = f.id
LEFT JOIN users u on fm.user_id = u.id
GROUP BY f.id, f.name, f.created_at, f.is_active
ORDER BY f.created_at DESC
LIMIT 5
`

type ListRecentFamiliesRow struct {
	IDFamilia    int32        `json:"id_familia"`
	NomeFamilia  string       `json:"nome_familia"`
	CreatedAt    string       `json:"created_at"`
	Status       sql.NullBool `json:"status"`
	TotalMembros int64        `json:"total_membros"`
}

func (q *Queries) ListRecentFamilies(ctx context.Context) ([]ListRecentFamiliesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentFamilies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentFamiliesRow
	for rows.Next() {
		var i ListRecentFamiliesRow
		if err := rows.Scan(
			&i.IDFamilia,
			&i.NomeFamilia,
			&i.CreatedAt,
			&i.Status,
			&i.TotalMembros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
