// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountFamilies(ctx context.Context, userID sql.NullString) (int64, error)
	CountTasksCompletedToday(ctx context.Context, userID sql.NullString) (int64, error)
	CountTasksPending(ctx context.Context) (int64, error)
	CountUsersFamilyMembers(ctx context.Context, userID sql.NullString) (int64, error)
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (sql.Result, error)
	CreateFamilyMember(ctx context.Context, arg CreateFamilyMemberParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DashboardPage(ctx context.Context, userID sql.NullString) ([]DashboardPageRow, error)
	GetFamiliesByUserID(ctx context.Context, userID sql.NullString) ([]Family, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetTaskStatus(ctx context.Context) ([]TaskStatus, error)
	GetTasksByFamily(ctx context.Context, familyID sql.NullInt32) ([]GetTasksByFamilyRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetWeeklyTaskCompletionStats(ctx context.Context) ([]GetWeeklyTaskCompletionStatsRow, error)
	ListFamiliesForUser(ctx context.Context, userID sql.NullString) ([]ListFamiliesForUserRow, error)
	ListRecentFamilies(ctx context.Context) ([]ListRecentFamiliesRow, error)
}

var _ Querier = (*Queries)(nil)
